version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: "redis"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

